dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.3
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.3
  - chiru-labs/ERC721A-Upgradeable@4.2.3
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.3'
      - '@openzeppelinupgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.3'
      - 'erc721a-upgradeable=chiru-labs/ERC721A-Upgradeable@4.2.3'
      - 'solady=./lib/solady'
      - 'scatter=./lib/scatter-contracts'
      - 'closedsea=./lib/closedsea'
      - '@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.3/contracts'
      - './ERC721A__OwnableUpgradeable.sol=./lib/scatter-contracts/contracts/ERC721A__OwnableUpgradeable.sol'

dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
  test1: ${T1}
  test2: ${T2}
  test3: ${T3}
  test4: ${T4}
  test5: ${T5}
  test6: ${T6}
  test7: ${T7}
  test8: ${T8}
  test9: ${T9}

networks:
  goerli:
    verify: True
  mainnet:
    verify: True
  polygon-main:
    verify: True
  polygon-test:
    verify: True
